### ISSUE TITLE
Confirmed working with ASUS ROG Zephyrus M (GM501)

### ISSUE THREAD

**Issue by thorhop** [wroberts/rogauracore#1]
Taking line **415** in **src/rogauracore.c**
`const uint16_t ASUS_PRODUCT_IDS[] = { 0x1854, 0x1869 };`

And adding the Product ID **0x1866**
`const uint16_t ASUS_PRODUCT_IDS[] = { 0x1854, 0x1869, 0x1866 };`

Makes the code work on the Zephyrus M (GM501).

**Comment by wroberts** [comment]
Beautiful!  Thanks for the PRs.  Merged.
