### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by fedorusov** [wroberts/rogauracore#21]
>Clone the github repo and enter the top-level directory. Then:
```
autoreconf -i
./configure
make
```
Here, I suppose autoreconf produces Makefile without `LIBS = -lusb-1.0` if it is not installed, so `make` fails. So I inserted it manually

**Comment by wroberts** [comment]
I hope this might be fixed with 5a42cf9.

**Comment by fedorusov** [comment]
Looks like it.
