### ISSUE TITLE
Error during make command

### ISSUE THREAD

**Issue by adityabisoi** [wroberts/rogauracore#31]
Error : ```initializer element is not constant``` during making the file (```make``` command). 

The todo here is : 
```
The error is in src/rogauracore.c, where SPEED and BRIGHTNESS are defined as
const. Using macro definitions instead to define them as constants may help.
```

**Comment by JoshDreamland** [comment]
Hi, can you try the patch in #32?

**Comment by JoshDreamland** [comment]
It's merged, now. Mind just doing a `git pull` and trying again?

**Comment by adityabisoi** [comment]
Ok cool !
