### ISSUE TITLE
Turn off RGB bar under the keyboard

### ISSUE THREAD

**Issue by diegoara96** [wroberts/rogauracore#34]
Is there a function to turn off the RGB bar under the keyboard?
At the moment I'm modifying the raibow function with

 `  
void
rainbow(Arguments *args, Messages *messages) {
    memcpy(args->colors, WHITE, 3);
    multi_static(args, messages);
}
`
so that only the keyboard lights up.

**Comment by boogiefromzk** [comment]
I have successfully turned off both, the keyboard and the bar under it with the following command:
sudo /usr/local/bin/rogauracore brightness 0
@wroberts, thank you very much! That lets me finally delete Windows partition :)
