### ISSUE TITLE
not working on GL503VS 

### ISSUE THREAD

**Issue by kymbl** [wroberts/rogauracore#58]
![image](https://user-images.githubusercontent.com/57202585/98437870-f20e5000-20f6-11eb-9eea-1aa7ca4906b8.png)

My machine can't run it, I tried a couple of things but it didn't work.

**Comment by wroberts** [comment]
@kymbl you'll need to do `make install` to get `rogauracore` on your path.  if you don't want to do that, you can just build the binary in the current directory with `make`, but then you need to give the relative path to the binary to run it: `./rogauaracore --help`.  Hope that helps!

**Comment by kymbl** [comment]
![image](https://user-images.githubusercontent.com/57202585/98442894-dddb4a80-2118-11eb-925b-025afd3717a9.png)
If you mean this, I can't do it either.

**Comment by kymbl** [comment]
I don't know how to use `make`, I would be so appreciated if you could teach me how to.

**Comment by JoshDreamland** [comment]
Make is not a package manager; it only builds what is in the specified makefile (or, by default, the file named Makefile in the current directory).

Have you tried following the installation instructions from the readme displayed on the [main project page](https://github.com/wroberts/rogauracore)?

**Comment by kymbl** [comment]
Okay, let me show you all the things I have done so far.
First of all, I have cloned the repository to my beloved pc, then downloaded the zip file and extracted it to the desktop.

![image](https://user-images.githubusercontent.com/57202585/98458880-3278d700-21a6-11eb-9c5e-54b4bdf37dca.png)


Then, I actually just tried to copy-paste the `On Ubuntu from a release:` part, but there seem to be errors that I don't have a clue how to get rid of even though I have been struggling to understand why this error occurs for a day now.

![image](https://user-images.githubusercontent.com/57202585/98458944-ce0a4780-21a6-11eb-8266-2110a8bb4f1c.png)

**Comment by wroberts** [comment]
The bit where it says `checking whether the C compiler works ... no` makes it look like either you don't have all the standard linux build tools installed or there is some kind of configuration problem with your setup.  You can try `sudo apt install --reinstall build-essential gcc` and retry `./configure` and `make`.  If that doesn't work you might try running `sudo dpkg-reconfigure build-essential` and `sudo dpkg-reconfigure gcc`.

**Comment by kymbl** [comment]
Oh, can't say how much thankful I am. `sudo apt install --reinstall build-essential gcc` worked flawlessly. After reinstallation, the problem has solved. Thanks again.

**Comment by wroberts** [comment]
Very cool, I'm glad you got things working :)
