### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by DuskTails** [wroberts/rogauracore#66]
Sorry to trouble you, this looks like a noob mistake to me but I don't know what I did wrong after I followed the clone method. Configure and make worked fine after installing the C compiler. Any clues?

**Comment by JoshDreamland** [comment]
Unless you ran `sudo make install`, the binary will only exist where you built it. You should be able to run it from within that directory without installing it, though.

**Comment by DuskTails** [comment]
@JoshDreamland That did it! Thank you so much, I'm glad I can finally change my keyboard now!
